---
title: "Analyze Simulations"
freeze: false
---

```{r}
library(tidyverse)
library(patchwork)

theme_set(cowplot::theme_cowplot(font_size=12,
                                 font_family = "Helvetica"))
```

```{r}
df <- arrow::read_parquet("accre_combined.parquet")
```

```{r}
selected_xcov <- 0.9

df <-
  df |> filter(x_cov == selected_xcov)
```


```{r}
plot_df <- 
df |>
  summarise(posterior_mean = mean(beta_x_e),
            .by = c("model", "dataset"))


create_summary_df <- function(df){
  summary_df <-
  df |>
  summarise(posterior_mean_mean = format(mean(posterior_mean), digits = 3),
            posterior_mean_median = format(median(posterior_mean), digits = 3),
            posterior_mean_sd = format(sd(posterior_mean), digits = 3),
            .by = "model")

  summary_df$posterior_mean_mean <- map_chr(summary_df$posterior_mean_mean, ~glue::glue("Mean: {.x}"))
  summary_df$posterior_mean_median <- map_chr(summary_df$posterior_mean_median, ~glue::glue("Median: {.x}"))
  summary_df$posterior_mean_sd <- map_chr(summary_df$posterior_mean_sd, ~glue::glue("SD: {.x}"))
  return(summary_df)
}
```

# Data Wrangling

```{r}
summary_df <- create_summary_df(plot_df)
```

# Histograms Posterior Mean

## Low

```{r}
fig <-
plot_df |>
  ggplot() +
  aes(x = posterior_mean, y = after_stat(density)) +
  geom_histogram(bins = 200, fill = "lightgray", color = "black") +
  geom_vline(xintercept = 1, linetype = 2) +
  geom_text(mapping = aes(label = posterior_mean_mean, x = 5, y = 0.8),
            size = 3.2,
            data = summary_df) +
  geom_text(mapping = aes(label = posterior_mean_median, x = 5, y = 0.5),
            size = 3.2,
            data = summary_df) +
  geom_text(mapping = aes(label = posterior_mean_sd, x = 5, y = 0.2),
            size = 3.2,
            data = summary_df) +
  facet_wrap(~model, ncol=1) +
  #coord_cartesian(xlim = c(-1, 6), ylim = c(0, 1.6)) +
  #scale_x_continuous(breaks = -1:6) +
  #scale_y_continuous(breaks = seq(0, 1.5, length.out = 4)) +
  labs(title = glue::glue("Estimated sampling distribution with Cov(x_e, x_z) = {selected_xcov}"),
       subtitle = "Design: Intercept Sampling\nSample Size: 500\nProportion Sampled: 25%\nParameter: Beta X_e\nEstimator: Posterior Mean",
       x = "Posterior Mean",
       y = "Density",
       caption = "Number of simulations: 2000")

ggsave(
  fig,
  filename = glue::glue("figures/histogram_scenario_{selected_xcov}.png"), 
  bg = "white",
  device = ragg::agg_png,
  units="in",
  height = 8,
  width=8,
  dpi=500)
```
