---
title: "Test Data Simulation Functions"
---

```{r}
library(bayes2stage)
library(tidyverse)
library(lme4)

# Set global ggplot theme
theme_set(cowplot::theme_cowplot(font_size=12,
                                 font_family = "Helvetica"))
```

```{r}
df <-
bayes2stage::generate_mixed_effects_data(N = 50000,
                                         Ms = c(4,5,6,7),
                                         alpha_main = 1.2,
                                         beta_x_e = 1.4,
                                         beta_x_z = 1.6,
                                         beta_t = 1.8,
                                         beta_t_xe_interaction = 1,
                                         error_sd = 2.2,
                                         rand_intercept_sd = 2.4,
                                         rand_slope_sd = 2.6,
                                         rand_eff_corr = 0.5,
                                         x_cov = 0.6,
                                         xe_var = 1,
                                         xz_var = 1)
```

```{r}
mod <- lme4::lmer(y ~ x_e + x_z + t + t:x_e + (1 + t | id),
                  data = df)
```

```{r}
summary(mod)
```

