---
title: "Test Two-Stage sampling functions"
---

```{r}
library(tidyverse)
library(patchwork)


# Set global ggplot theme
ggplot2::theme_set(cowplot::theme_cowplot(font_size=12,
                                 font_family = "Helvetica"))
```

# Generate Data

```{r}
df <-
bayes2stage::generate_mixed_effects_data(N = 500,
                                         Ms = 5,
                                         alpha_main = 0,
                                         beta_x_e = 0,
                                         beta_x_z = 0,
                                         beta_t = 1,
                                         beta_t_xe_interaction = 0,
                                         error_sd = 1,
                                         rand_intercept_sd = 4,
                                         rand_slope_sd = 2,
                                         rand_eff_corr = 0,
                                         x_cov = 0,
                                         xe_var = 1,
                                         xz_var = 1)
```

# ODS

```{r}
intercept_df <- bayes2stage::ods_design(df, type = "intercept")
slope_df <- bayes2stage::ods_design(df, type = "slope")
```

## Selection plots

```{r}
selected_plot_ods_intercept <-
intercept_df |>
  ggplot() +
  aes(x = t, y = y, group = id, color = selected) +
  geom_line(linewidth = 0.1) +
  geom_hline(yintercept = 0, linetype = 2) +
  scale_color_manual(values = c("gray", "red"))+
  labs(title = "Intercept Sampling", color = "Selected in stage 2")

selected_plot_ods_slope <-
slope_df |>
  ggplot() +
  aes(x = t, y = y, group = id, color = selected) +
  geom_line(linewidth = 0.1) +
  geom_hline(yintercept = 0, linetype = 2) +
  scale_color_manual(values = c("gray", "red"))+
  labs(title = "Slope Sampling", color = "Selected in stage 2")
```

```{r}
selected_plot_ods_intercept / selected_plot_ods_slope
```

# BDS

```{r}
intercept_df <- bayes2stage::bds_design(df, type = "intercept")
slope_df <- bayes2stage::bds_design(df, type = "slope")
```

## Selection plots

```{r}
selected_plot_bds_intercept <-
intercept_df |>
  ggplot() +
  aes(x = t, y = y, group = id, color = selected) +
  geom_line(linewidth = 0.1) +
  geom_hline(yintercept = 0, linetype = 2) +
  scale_color_manual(values = c("gray", "red"))+
  labs(title = "Intercept Sampling", color = "Selected in stage 2")

selected_plot_bds_slope <-
slope_df |>
  ggplot() +
  aes(x = t, y = y, group = id, color = selected) +
  geom_line(linewidth = 0.1) +
  geom_hline(yintercept = 0, linetype = 2) +
  scale_color_manual(values = c("gray", "red"))+
  labs(title = "Slope Sampling", color = "Selected in stage 2")
```

```{r}
selected_plot_bds_intercept / selected_plot_bds_slope
```

# SRS

```{r}
selected_plot_srs <-
bayes2stage::srs_design(df, 0.25) |>
  ggplot() +
  aes(x = t, y = y, group = id, color = selected) +
  geom_line(linewidth = 0.1) +
  geom_hline(yintercept = 0, linetype = 2) +
  scale_color_manual(values = c("gray", "red"))+
  labs(title = "Intercept Sampling", color = "Selected in stage 2")
```

```{r}
selected_plot_srs
```



