---
title: "Test Stan Model"
---

```{r}
library(tidyverse)
library(cmdstanr)
```

```{r}
model <- cmdstanr::cmdstan_model(stan_file = "../stan/mixed_effects_imputation.stan")
```

```{r}
df <-
bayes2stage::generate_mixed_effects_data(N = 1000,
                                         Ms = c(5),
                                         alpha_main = 1.2,
                                         beta_x_e = 1.4,
                                         beta_x_z = 1.6,
                                         beta_t = 1.8,
                                         beta_t_xe_interaction = 1,
                                         error_sd = 2.2,
                                         rand_intercept_sd = 2.4,
                                         rand_slope_sd = 2.6,
                                         rand_eff_corr = 0.5,
                                         x_cov = 0.6,
                                         xe_var = 1,
                                         xz_var = 1)
```

```{r}
fit_full <- model$sample(data = bayes2stage::create_stan_data(df),
                         chains = 8,
                         parallel_chains = 8,
                         iter_warmup = 1000,
                         iter_sampling = 1000)
```

```{r}
draws <- fit_full$draws(variables = c("corr_rand_effects[1,1]", "corr_rand_effects[2,1]", "beta_x_e", "beta[1]", "beta_t", "sigma_rand_effects[1]", "sigma_rand_effects[2]"),
                 format = "df")

rethinking::HPDI(draws$`beta_t`)
rethinking::HPDI(draws$`beta_x_e`)
rethinking::HPDI(draws$`beta[1]`)
rethinking::HPDI(draws$`sigma_rand_effects[1]`)
rethinking::HPDI(draws$`sigma_rand_effects[2]`)
rethinking::HPDI(draws$`corr_rand_effects[2,1]`)
```


